version: "3"
services:
  api:
    container_name: "api"
    build: . 
    environment:
      URI_DATABASE: "host=127.0.0.1 port=5432 user=root dbname=postgres password=root sslmode=disable"
    ports:
      - 8182:8182