// Code generated by entc, DO NOT EDIT.

package product

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIDCategories holds the string denoting the id_categories field in the database.
	FieldIDCategories = "id_categories"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStock holds the string denoting the stock field in the database.
	FieldStock = "stock"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeCategories holds the string denoting the categories edge name in mutations.
	EdgeCategories = "categories"
	// Table holds the table name of the product in the database.
	Table = "products"
	// CategoriesTable is the table that holds the categories relation/edge.
	CategoriesTable = "products"
	// CategoriesInverseTable is the table name for the Categories entity.
	// It exists in this package in order to avoid circular dependency with the "categories" package.
	CategoriesInverseTable = "categories"
	// CategoriesColumn is the table column denoting the categories relation/edge.
	CategoriesColumn = "id_categories"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldIDCategories,
	FieldPrice,
	FieldName,
	FieldStock,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// StockValidator is a validator for the "stock" field. It is called by the builders before save.
	StockValidator func(int64) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
)
