// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Categories is the predicate function for categories builders.
type Categories func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
